# Generated by Django 3.1.7 on 2021-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210323_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='city',
            field=models.CharField(choices=[('Calgary', 'Calgary'), ('Edmonton', 'Edmonton')], default='Calgary', max_length=222),
        ),
    ]
